### ISSUE TITLE
Pre-rendering

### ISSUE THREAD

**Issue by jamesjwarren** [thisissoon/FM-Frontend-API#6]
We could use this prerender middleware for express to provide pre-rendered views https://github.com/prerender/prerender-node

**Comment by edoparearyee** [comment]
@jamesjwarren gonna take a look at this if your not already as this looks like a quick win. Think we may need to remove HTML5 location to get it too work.

**Comment by jamesjwarren** [comment]
@edwardoparearyee go ahead :smile:
